--Просмотр доступных расширений
select * from pg_available_extensions;
 
--Если install_version is not null и тд. заполнен, то данное расширение уже установлено
--По умолчанию изначально установлено только расширение plpgsql - "PL/pgSQL procedural language"(позволяет работать с языком запросов plsql)
--Большинство остальных доступных расширений можно установить через простое
--CREATE EXTENSION <Name extension>;
--Но ряд расширений относится к shared preload libraries, такие модули надо отдельно прописывать в postgresql.conf. Использовать LOAD нельзя.
--Включение pg_stat_statements
 
#Добавим в postgresql.conf следующие строки
shared_preload_libraries = 'pg_stat_statements'
 
# Increase the max size of the query strings Postgres records
track_activity_query_size = 2048
 
# Track statements generated by stored procedures as well
pg_stat_statements.track = all
 
--Сохраняем изменения и далее необходимо произвести через команды ОС рестарт сервиса postgresql
sudo service postgresql restart
 
--Далее на нужной БД выполняем
CREATE EXTENSION pg_stat_statements;